<a href="https://colab.research.google.com/github/Suresh-katari-NRIDegree/python-mini-project-/blob/main/intraduction_to_numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

In [20]:
# Recap
arr = np.array([[1,2,3],[4,5,6]])

In [4]:
type(arr)

numpy.ndarray

In [45]:
# Dot product - n x n || n x p
arr1 = np.random.randint(1,2,(3,1))

In [46]:
arr.shape
arr1.shape

(3, 1)

In [48]:
arr.size

3

In [67]:
result = np.dot(arr1.T, arr)


In [68]:
print(result)

[[3]]


In [82]:
r1 = np.random.randint(10,20,(4,5))
print(r1)

[[17 14 15 13 17]
 [10 17 16 19 15]
 [17 17 16 16 12]
 [10 15 12 17 15]]


In [83]:
r2 = np.eye(4)
print(r2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [86]:
# r1. I
result2 = np.dot(r2,r1)

In [87]:
print(result2)

[[17. 14. 15. 13. 17.]
 [10. 17. 16. 19. 15.]
 [17. 17. 16. 16. 12.]
 [10. 15. 12. 17. 15.]]


In [88]:
# M. I = I. M = M

In [89]:
# A-B ! = B.A

In [90]:
# Mathematical operations
# + - /
t1 = np.random.randint(1,10,(3,3))
t2 = np.random.randint(1,10,(3,3))

In [91]:
print(t1)
print(t2)

[[7 4 5]
 [7 1 5]
 [2 4 3]]
[[5 7 5]
 [9 5 3]
 [2 7 2]]


In [92]:
t3 = t1 + t2
print(t3)

[[12 11 10]
 [16  6  8]
 [ 4 11  5]]


In [93]:
# Matrix Multiplication
result = np.dot(arr1,arr2)

In [94]:
# statistical data
mean = t3.mean()
max = t3.max()
min = t3.min()
std = t3.std()
var = t3.var()


In [95]:
print(var)

13.061728395061728


In [96]:
print(std)

3.614101326064576


In [97]:
std * std

13.061728395061726

In [98]:
# trigunmetrics functions
# sin(x)
# cos(x)
# tan(x) - sin(x)\cas(x)
# cosec -
# ses - 1 \ cos(x)
#cot -  1 \tan(x)
angles = np.array([0,30,45,60,90])
result = np.sin(np.radians(angles))
result1 = np.cos(np.radians(angles))
result2 = np.tan(np.radians(angles))


In [80]:
# flliting
# flliting
import numpy as np
arr = np.array([10,20,40,30])

farr = arr[arr>20]

print(farr)

[40 30]
